#!/usr/bin/env python3
"""
Email Configuration Setup Script
This script helps you set up SMTP email configuration for the notification system.
"""

import os

def setup_email_config():
    """Create .env file with email configuration"""
    
    print("=" * 60)
    print("Email Configuration Setup")
    print("=" * 60)
    print("\nThis script will help you configure SMTP email settings.")
    print("You'll need a Gmail account with App Password enabled.\n")
    
    # Check if .env already exists
    if os.path.exists('.env'):
        response = input(".env file already exists. Overwrite? (y/n): ").strip().lower()
        if response != 'y':
            print("Cancelled. Exiting...")
            return
    
    # Get SMTP configuration
    print("\n--- SMTP Configuration ---")
    smtp_server = input("SMTP Server [smtp.gmail.com]: ").strip() or "smtp.gmail.com"
    smtp_port = input("SMTP Port [587]: ").strip() or "587"
    email_username = input("Your Gmail address: ").strip()
    
    if not email_username:
        print("Error: Gmail address is required!")
        return
    
    print("\n--- Gmail App Password Setup ---")
    print("To get your Gmail App Password:")
    print("1. Go to https://myaccount.google.com/security")
    print("2. Enable 2-Step Verification (if not already enabled)")
    print("3. Go to App Passwords: https://myaccount.google.com/apppasswords")
    print("4. Generate a new app password for 'Mail'")
    print("5. Copy the 16-character password\n")
    
    email_password = input("Gmail App Password (16 characters): ").strip()
    
    if not email_password:
        print("Error: App Password is required!")
        return
    
    # Create .env file content
    env_content = f"""# Email Configuration for SMTP
# Generated by setup_email_config.py

SMTP_SERVER={smtp_server}
SMTP_PORT={smtp_port}
EMAIL_USERNAME={email_username}
EMAIL_PASSWORD={email_password}

# Note: This file contains sensitive information. Do not commit it to git!
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n" + "=" * 60)
        print("✅ Email configuration saved to .env file!")
        print("=" * 60)
        print("\nNext steps:")
        print("1. Install python-dotenv: pip install python-dotenv")
        print("2. Restart your application")
        print("3. Test by sending a notification from instructor dashboard")
        print("\n⚠️  Important: Add .env to .gitignore to keep your credentials safe!")
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")

if __name__ == "__main__":
    setup_email_config()

